//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hajloo.FOSS.UnicodeConverter.Web.UI.Master {
    
    
    public partial class Portal {
        
        /// <summary>
        /// HeadContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        
        /// <summary>
        /// UnicodeConverterform control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm UnicodeConverterform;
        
        /// <summary>
        /// UnicodeConverterScriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager UnicodeConverterScriptManager;
        
        /// <summary>
        /// lnbConvertToUnicode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnbConvertToUnicode;
        
        /// <summary>
        /// lnbConvertFromUnicode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnbConvertFromUnicode;
        
        /// <summary>
        /// lnbUnicodeInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnbUnicodeInformation;
        
        /// <summary>
        /// lnbStandards control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnbStandards;
        
        /// <summary>
        /// lnbHelpAndHowTo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnbHelpAndHowTo;
        
        /// <summary>
        /// lnbAbout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnbAbout;
        
        /// <summary>
        /// AboutControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hajloo.FOSS.UnicodeConverter.Web.UI.Modules.About AboutControl;
        
        /// <summary>
        /// ConvertFromUnicode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hajloo.FOSS.UnicodeConverter.Web.UI.Modules.ConvertFromUnicode ConvertFromUnicode;
        
        /// <summary>
        /// ConvertToUnicode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hajloo.FOSS.UnicodeConverter.Web.UI.Modules.ConvertToUnicode ConvertToUnicode;
        
        /// <summary>
        /// StandardsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hajloo.FOSS.UnicodeConverter.Web.UI.Modules.Standards StandardsControl;
        
        /// <summary>
        /// UnicodeInformationControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hajloo.FOSS.UnicodeConverter.Web.UI.Modules.UnicodeInformation UnicodeInformationControl;
        
        /// <summary>
        /// HelpAndHowToControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hajloo.FOSS.UnicodeConverter.Web.UI.Modules.HelpAndHowTo HelpAndHowToControl;
    }
}
