//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommonResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog :.
        /// </summary>
        internal static string AboutBlogLabel {
            get {
                return ResourceManager.GetString("AboutBlogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Converter is a free open source software for converting to/from unicode and also getting information about a character..
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers and Designers :.
        /// </summary>
        internal static string AboutDevelopersLabel {
            get {
                return ResourceManager.GetString("AboutDevelopersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Mail :.
        /// </summary>
        internal static string AbouteMailLabel {
            get {
                return ResourceManager.GetString("AbouteMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Version Date :.
        /// </summary>
        internal static string AboutLastVersionLabel {
            get {
                return ResourceManager.GetString("AboutLastVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Host :.
        /// </summary>
        internal static string AboutProjectHostLabel {
            get {
                return ResourceManager.GetString("AboutProjectHostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project License :.
        /// </summary>
        internal static string AboutProjectLicenseLabel {
            get {
                return ResourceManager.GetString("AboutProjectLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager :.
        /// </summary>
        internal static string AboutProjectManagerLabel {
            get {
                return ResourceManager.GetString("AboutProjectManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL :.
        /// </summary>
        internal static string AboutProjectURL {
            get {
                return ResourceManager.GetString("AboutProjectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Unicode Converter.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version :.
        /// </summary>
        internal static string AboutVersionLabel {
            get {
                return ResourceManager.GetString("AboutVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTR.
        /// </summary>
        internal static string ApplicationDirection {
            get {
                return ResourceManager.GetString("ApplicationDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert From Unicode.
        /// </summary>
        internal static string ConvertFromUnicode {
            get {
                return ResourceManager.GetString("ConvertFromUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        internal static string ConvertFromUnicodeDeCode {
            get {
                return ResourceManager.GetString("ConvertFromUnicodeDeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To decode a byte or a bytecode stream back to Original unicode scheme, put the code or bytecode into the Bytes box and then press the Decode button. note that you should put the correct byte code into the Bytes box, each unicode character have four digit, for example 066C represent for &apos;ی&apos; and if you put just 66C you may face another character. so in the string that you put into the Bytes box, check the codes. for more info about each character you can use from Unicode Information Tab..
        /// </summary>
        internal static string ConvertFromUnicodeMainText {
            get {
                return ResourceManager.GetString("ConvertFromUnicodeMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert From Unicode.
        /// </summary>
        internal static string ConvertFromUnicodeTitle {
            get {
                return ResourceManager.GetString("ConvertFromUnicodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert To Unicode.
        /// </summary>
        internal static string ConvertToUnicode {
            get {
                return ResourceManager.GetString("ConvertToUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string ConvertToUnicodeConvert {
            get {
                return ResourceManager.GetString("ConvertToUnicodeConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex Code :.
        /// </summary>
        internal static string ConvertToUnicodeHexCode {
            get {
                return ResourceManager.GetString("ConvertToUnicodeHexCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To convert a character, word, Scentense or a paragraph enter put your text within the Words box and then press Convert Button. the Unicode per character code, will display in the result box. note that what you see and the result may be different, it is a commonly event. for resolving this issue you can select an exact part of generated result code, and then put it in the Convert From Unicode Section, then compare the unicode Character Code, and Your special Character and the character that application has g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertToUnicodeMainText {
            get {
                return ResourceManager.GetString("ConvertToUnicodeMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert To Unicode.
        /// </summary>
        internal static string ConvertToUnicodeTitle {
            get {
                return ResourceManager.GetString("ConvertToUnicodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words :.
        /// </summary>
        internal static string ConvertToUnicodeWords {
            get {
                return ResourceManager.GetString("ConvertToUnicodeWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help And How To.
        /// </summary>
        internal static string HelpAndHowTo {
            get {
                return ResourceManager.GetString("HelpAndHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standards.
        /// </summary>
        internal static string Standards {
            get {
                return ResourceManager.GetString("Standards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Keyboard Layout Information.
        /// </summary>
        internal static string StandardsListResultTitle {
            get {
                return ResourceManager.GetString("StandardsListResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string StandardsListTopTitle {
            get {
                return ResourceManager.GetString("StandardsListTopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        internal static string StandardsList_Country {
            get {
                return ResourceManager.GetString("StandardsList_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Layout :.
        /// </summary>
        internal static string StandardsList_KeyboardLayout {
            get {
                return ResourceManager.GetString("StandardsList_KeyboardLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License :.
        /// </summary>
        internal static string StandardsList_License {
            get {
                return ResourceManager.GetString("StandardsList_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer :.
        /// </summary>
        internal static string StandardsList_Producer {
            get {
                return ResourceManager.GetString("StandardsList_Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL :.
        /// </summary>
        internal static string StandardsList_ProjectURL {
            get {
                return ResourceManager.GetString("StandardsList_ProjectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referer :.
        /// </summary>
        internal static string StandardsList_Referer {
            get {
                return ResourceManager.GetString("StandardsList_Referer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referer Mail :.
        /// </summary>
        internal static string StandardsList_RefererMail {
            get {
                return ResourceManager.GetString("StandardsList_RefererMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Date :.
        /// </summary>
        internal static string StandardsList_StandardDate {
            get {
                return ResourceManager.GetString("StandardsList_StandardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standards and Documentation.
        /// </summary>
        internal static string StandardsTitle {
            get {
                return ResourceManager.GetString("StandardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Information.
        /// </summary>
        internal static string UnicodeInformation {
            get {
                return ResourceManager.GetString("UnicodeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Word.
        /// </summary>
        internal static string UnicodeInformationAddToWordButton {
            get {
                return ResourceManager.GetString("UnicodeInformationAddToWordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category :.
        /// </summary>
        internal static string UnicodeInformationCategoryLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char :.
        /// </summary>
        internal static string UnicodeInformationCharLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationCharLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal :.
        /// </summary>
        internal static string UnicodeInformationDecimalLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationDecimalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string UnicodeInformationGetDecimalInfoButton {
            get {
                return ResourceManager.GetString("UnicodeInformationGetDecimalInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string UnicodeInformationGetHexCodeInfoButton {
            get {
                return ResourceManager.GetString("UnicodeInformationGetHexCodeInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex Code :.
        /// </summary>
        internal static string UnicodeInformationHexCodeLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationHexCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string UnicodeInformationInformationButton {
            get {
                return ResourceManager.GetString("UnicodeInformationInformationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is BIDI ?.
        /// </summary>
        internal static string UnicodeInformationIsBidiLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationIsBidiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string UnicodeInformationNameLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range :.
        /// </summary>
        internal static string UnicodeInformationRangeLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Hex Code and Final Text.
        /// </summary>
        internal static string UnicodeInformationResultsLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape :.
        /// </summary>
        internal static string UnicodeInformationShapeLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationShapeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Information.
        /// </summary>
        internal static string UnicodeInformationTitle {
            get {
                return ResourceManager.GetString("UnicodeInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type :.
        /// </summary>
        internal static string UnicodeInformationTypeLabel {
            get {
                return ResourceManager.GetString("UnicodeInformationTypeLabel", resourceCulture);
            }
        }
    }
}
